name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --build-arg NEXT_PUBLIC_TEXT_RAZOR_API_KEY=${{ secrets.NEXT_PUBLIC_TEXT_RAZOR_API_KEY }} -t text-analyzer .

      - name: Tag Docker image
        run: |
          docker tag text-analyzer "${{ secrets.DOCKER_USERNAME }}/text-analyzer:latest"

      - name: Push Docker image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/text-analyzer:latest"

      - name: SSH to server and run Docker container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}/text-analyzer:latest"

            docker stop text-analyzer || true
            docker rm text-analyzer || true

            docker run -d \
              --restart unless-stopped \
              -p 3001:3001 \
              --name text-analyzer \
              ${{ secrets.DOCKER_USERNAME }}/text-analyzer:latest
